// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wMolhMtSzES_PAcxd4rSV4TPWIxuY6Y',
    appId: '1:1058858972974:web:189982d0c8abeb95d0acbf',
    messagingSenderId: '1058858972974',
    projectId: 'flutterfirebaseauth-632da',
    authDomain: 'flutterfirebaseauth-632da.firebaseapp.com',
    storageBucket: 'flutterfirebaseauth-632da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo-ovugy8BOR0Ji4DXOl1edHeay-lCNTY',
    appId: '1:1058858972974:android:9869b93e4bbe6626d0acbf',
    messagingSenderId: '1058858972974',
    projectId: 'flutterfirebaseauth-632da',
    storageBucket: 'flutterfirebaseauth-632da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_Z64lCgfw4Dqljma6uSQCjGD4gL_ag4',
    appId: '1:1058858972974:ios:753a4692137c0544d0acbf',
    messagingSenderId: '1058858972974',
    projectId: 'flutterfirebaseauth-632da',
    storageBucket: 'flutterfirebaseauth-632da.appspot.com',
    iosClientId: '1058858972974-msn459tu2use7g44go6aohem4ijq12nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP_Z64lCgfw4Dqljma6uSQCjGD4gL_ag4',
    appId: '1:1058858972974:ios:adfb8a29e1ffda44d0acbf',
    messagingSenderId: '1058858972974',
    projectId: 'flutterfirebaseauth-632da',
    storageBucket: 'flutterfirebaseauth-632da.appspot.com',
    iosClientId: '1058858972974-a334cpg9r6jlo4qkqt1tb468vlvlh27a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth.RunnerTests',
  );
}
